version: '3'
services:
  app:
    build:
      context: ./
    image: image-preload-polyfill-app
    container_name: container-preload-polyfill-app
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html
    tty: true
